name: build

on:
  push:
    branches: [ master, v2 ]
  pull_request:
    branches: [ master, v2 ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: deps
        run:  make deps
      - name: static program analysis
        run: make fmt-check vet
      - name: build
        run: make build
      - name: test
        run: make test
      - name: coverage
        run: bash <(curl -s https://codecov.io/bash)
